/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as DataSecurityRouteImport } from './routes/data-security'
import { Route as DashboardImageRouteImport } from './routes/dashboard-image'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSecurityRoute = DataSecurityRouteImport.update({
  id: '/data-security',
  path: '/data-security',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardImageRoute = DashboardImageRouteImport.update({
  id: '/dashboard-image',
  path: '/dashboard-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard-image': typeof DashboardImageRoute
  '/data-security': typeof DataSecurityRoute
  '/investors': typeof InvestorsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard-image': typeof DashboardImageRoute
  '/data-security': typeof DataSecurityRoute
  '/investors': typeof InvestorsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard-image': typeof DashboardImageRoute
  '/data-security': typeof DataSecurityRoute
  '/investors': typeof InvestorsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard-image'
    | '/data-security'
    | '/investors'
    | '/platform'
    | '/pricing'
    | '/privacy-policy'
    | '/solutions'
    | '/terms'
    | '/products/$slug'
    | '/resources/$slug'
    | '/solutions/$slug'
    | '/products/'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard-image'
    | '/data-security'
    | '/investors'
    | '/platform'
    | '/pricing'
    | '/privacy-policy'
    | '/solutions'
    | '/terms'
    | '/products/$slug'
    | '/resources/$slug'
    | '/solutions/$slug'
    | '/products'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard-image'
    | '/data-security'
    | '/investors'
    | '/platform'
    | '/pricing'
    | '/privacy-policy'
    | '/solutions'
    | '/terms'
    | '/products/$slug'
    | '/resources/$slug'
    | '/solutions/$slug'
    | '/products/'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DashboardImageRoute: typeof DashboardImageRoute
  DataSecurityRoute: typeof DataSecurityRoute
  InvestorsRoute: typeof InvestorsRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TermsRoute: typeof TermsRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-security': {
      id: '/data-security'
      path: '/data-security'
      fullPath: '/data-security'
      preLoaderRoute: typeof DataSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-image': {
      id: '/dashboard-image'
      path: '/dashboard-image'
      fullPath: '/dashboard-image'
      preLoaderRoute: typeof DashboardImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DashboardImageRoute: DashboardImageRoute,
  DataSecurityRoute: DataSecurityRoute,
  InvestorsRoute: InvestorsRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  TermsRoute: TermsRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
